//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public System.Guid CustomerGuid { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int LevelId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateOn { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public string LastIpAddress { get; set; }
        public bool Active { get; set; }
        public string PasswordSalt { get; set; }
    }
}
