//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendlyLink
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public bool ShowImage { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public bool target { get; set; }
        public string ImageURL { get; set; }
        public string Linkref { get; set; }
        public int DisplayOrder { get; set; }
        public bool Deleted { get; set; }
    }
}
